from __future__ import annotations

import cv2
import numpy as np
from scipy import fft

from .fft_utils import otf2psf, psf2otf
from .kernel import estimate_psf


def _normalize_positive(kernel: np.ndarray) -> np.ndarray:
    k = np.maximum(np.asarray(kernel, dtype=np.float32), 0.0).copy()
    total = float(k.sum())
    if total > 0:
        k /= total
    return k


def _skeletonize(mask: np.ndarray) -> np.ndarray:
    """Morphological skeletonization using only core OpenCV operations."""
    image = np.asarray(mask, dtype=np.uint8) * 255
    skeleton = np.zeros_like(image)
    element = cv2.getStructuringElement(cv2.MORPH_CROSS, (3, 3))
    for _ in range(max(mask.shape) * 2):
        eroded = cv2.erode(image, element)
        opened = cv2.dilate(eroded, element)
        skeleton = cv2.bitwise_or(skeleton, cv2.subtract(image, opened))
        image = eroded
        if cv2.countNonZero(image) == 0:
            break
    return skeleton > 0


def _infer_motion_corridor(
    seed: np.ndarray,
    *,
    corridor_radius: int = 2,
) -> np.ndarray:
    """Infer a thin connected trajectory corridor from a noisy warm-start PSF.

    Motion blur is generated by a continuous camera/object trajectory. Rather than
    assuming that trajectory is straight, this helper searches several support
    thresholds and small morphological closing radii, keeps a high-mass connected
    component, skeletonizes it, and dilates the skeleton into a narrow admissible
    corridor. The resulting mask can represent curved, bent, or self-intersecting
    motion while discarding isolated 2-D PSF noise.
    """
    if corridor_radius < 1:
        raise ValueError("corridor_radius must be >= 1")

    k = _normalize_positive(seed)
    if float(k.sum()) <= 0:
        mask = np.zeros(k.shape, dtype=bool)
        mask[k.shape[0] // 2, k.shape[1] // 2] = True
        return mask

    smooth = cv2.GaussianBlur(k, (0, 0), sigmaX=0.8, sigmaY=0.8)
    peak = float(smooth.max())
    if peak <= 0:
        return np.ones(k.shape, dtype=bool)

    corridor_element = cv2.getStructuringElement(
        cv2.MORPH_ELLIPSE,
        (2 * corridor_radius + 1, 2 * corridor_radius + 1),
    )
    best_mask: np.ndarray | None = None
    best_score = -np.inf

    # Several thresholds make the prior robust to both bright compact kernels and
    # long weak trajectories. The score rewards captured PSF mass while penalizing
    # large admissible area; a small bonus favors hypotheses retaining >=55% mass.
    for threshold_fraction in (0.05, 0.035, 0.025, 0.015, 0.008):
        support = smooth >= peak * threshold_fraction
        for close_radius in (1, 2, 3):
            close_element = cv2.getStructuringElement(
                cv2.MORPH_ELLIPSE,
                (2 * close_radius + 1, 2 * close_radius + 1),
            )
            closed = cv2.morphologyEx(
                support.astype(np.uint8),
                cv2.MORPH_CLOSE,
                close_element,
            )
            count, labels = cv2.connectedComponents(closed, connectivity=8)
            for label in range(1, count):
                component = labels == label
                component_mass = float(k[component].sum())
                if component_mass < 0.08:
                    continue

                skeleton = _skeletonize(component)
                if not np.any(skeleton):
                    skeleton = component
                corridor = cv2.dilate(skeleton.astype(np.uint8), corridor_element) > 0
                captured_mass = float(k[corridor].sum())
                area_fraction = float(np.mean(corridor))
                score = captured_mass - 0.45 * area_fraction
                if captured_mass >= 0.55:
                    score += 0.15
                if score > best_score:
                    best_score = score
                    best_mask = corridor

    if best_mask is None or not np.any(best_mask):
        # A rare extremely flat warm start carries no reliable trajectory cue. Keep
        # optimization well defined rather than inventing an arbitrary direction.
        return np.ones(k.shape, dtype=bool)
    return best_mask


def _project_masked_simplex(values: np.ndarray, mask: np.ndarray) -> np.ndarray:
    """Euclidean projection onto {k >= 0, sum(k)=1, k[~mask]=0}."""
    z = np.asarray(values, dtype=np.float64)
    support = np.asarray(mask, dtype=bool)
    v = z[support]
    if v.size == 0:
        raise ValueError("motion corridor must contain at least one pixel")

    ordered = np.sort(v)[::-1]
    cssv = np.cumsum(ordered) - 1.0
    indices = np.arange(1, ordered.size + 1, dtype=np.float64)
    active = ordered - cssv / indices > 0
    rho = np.flatnonzero(active)
    theta = cssv[int(rho[-1])] / float(rho[-1] + 1) if rho.size else cssv[-1] / v.size

    out = np.zeros_like(z)
    out[support] = np.maximum(v - theta, 0.0)
    total = float(out.sum())
    if total <= 0:
        yy, xx = np.nonzero(support)
        middle = len(yy) // 2
        out[yy[middle], xx[middle]] = 1.0
    else:
        out /= total
    return out


def _apply_normal_operator(
    kernel: np.ndarray,
    spectrum: np.ndarray,
    image_shape: tuple[int, int],
    weight: float,
    workers: int,
) -> np.ndarray:
    kernel_otf = psf2otf(kernel, image_shape, workers)
    return otf2psf(spectrum * kernel_otf, kernel.shape, workers) + weight * kernel


def estimate_motion_constrained_psf(
    blurred_x: np.ndarray,
    blurred_y: np.ndarray,
    latent_x: np.ndarray,
    latent_y: np.ndarray,
    weight: float,
    psf_shape: tuple[int, int],
    *,
    workers: int = -1,
    warm_start_iter: int = 20,
    projected_iter: int = 24,
    tol: float = 1e-6,
    corridor_radius: int = 2,
) -> np.ndarray:
    """Estimate a PSF under a continuous-motion trajectory restriction.

    The free PSF normal equation has one variable per kernel pixel, so noisy image
    gradients can create isolated side lobes that are mathematically convenient but
    physically implausible for motion blur. This estimator first obtains an
    unconstrained warm start only to infer a connected trajectory corridor, then
    solves the quadratic PSF objective with projected-gradient iterations subject to

        k >= 0,  sum(k) = 1,  support(k) subset trajectory_corridor.

    The corridor is skeleton-based rather than a straight-line model, so curved and
    compound camera motion remains representable while most of the 2-D search space
    is removed from the optimization.
    """
    if projected_iter < 1:
        raise ValueError("projected_iter must be >= 1")
    if warm_start_iter < 1:
        raise ValueError("warm_start_iter must be >= 1")

    warm = estimate_psf(
        blurred_x,
        blurred_y,
        latent_x,
        latent_y,
        weight,
        psf_shape,
        workers=workers,
        max_iter=warm_start_iter,
        tol=min(tol, 1e-5),
        peak_fraction=0.0,
    )
    corridor = _infer_motion_corridor(warm, corridor_radius=corridor_radius)

    lxf = fft.fft2(latent_x, workers=workers)
    lyf = fft.fft2(latent_y, workers=workers)
    bxf = fft.fft2(blurred_x, workers=workers)
    byf = fft.fft2(blurred_y, workers=workers)
    rhs = otf2psf(
        np.conj(lxf) * bxf + np.conj(lyf) * byf,
        psf_shape,
        workers,
    )
    spectrum = np.conj(lxf) * lxf + np.conj(lyf) * lyf

    kernel = _project_masked_simplex(np.maximum(warm, 0.0), corridor)
    # max(spectrum)+weight is a safe upper bound for the normal-operator norm;
    # using it keeps projected-gradient updates stable without an extra power solve.
    lipschitz = float(np.max(np.real(spectrum))) + float(weight)
    step = 0.9 / max(lipschitz, 1e-12)

    for _ in range(projected_iter):
        gradient = _apply_normal_operator(
            kernel,
            spectrum,
            blurred_x.shape,
            weight,
            workers,
        ) - rhs
        candidate = _project_masked_simplex(kernel - step * gradient, corridor)
        delta = float(np.linalg.norm(candidate - kernel))
        kernel = candidate
        if delta <= tol * max(1.0, float(np.linalg.norm(kernel))):
            break

    return kernel.astype(np.float32)
